@baseAddress = http://localhost:5277
@categoryId = 08de207d-7b91-9e38-80fa-5b4bb1920000
@courseId = 08de216c-b76c-888a-80fa-5b4bb1920000
@userId = b1920000-5b4b-80fa-a2aa-08de23baccdc

GET {{baseAddress}}/api/categories
Accept: application/json
###

POST {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "New Category v2",
  "description": "Test desc of the new category"
}
###

GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json
###

POST {{baseAddress}}/api/courses
Accept: application/json
Content-Type: application/json

{
  "name": "New Course",
  "description": "Description of the new course",
  "price": 49.99,
  "imageUrl": "http://example.com/course-image.jpg",
  "userId": "user123",
  "categoryId": "{{categoryId}}",
  "duration": 120
}
###

GET {{baseAddress}}/api/courses
Accept: application/json
###

GET {{baseAddress}}/api/courses/{{courseId}}
Accept: application/json
###

PUT {{baseAddress}}/api/courses
Accept: application/json
Content-Type: application/json

{
  "id": "{{courseId}}",
  "name": "New Course Update",
  "description": "Description of the new course",
  "price": 49.99,
  "imageUrl": "http://example.com/course-image.jpg",
  "userId": "user123",
  "categoryId": "{{categoryId}}",
  "duration": 120
}
###

DELETE {{baseAddress}}/api/courses/{{courseId}}
Accept: application/json
###

GET {{baseAddress}}/api/courses/user/{{userId}}
Accept: application/json
###